### ISSUE TITLE
Verbs ту and тӳ

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-chv#9]
Ту is defined as:
`ту:ту%{в%}                  V-TV;!""
`But `{в}` is not working properly in many cases.

`ту<v><tv><pres><p1><sg>` generates  туатӑп    instead of тӑватӑп
`ту<v><tv><pres><p2><sg>` generates  туатӑн    instead of тӑватӑн
`ту<v><tv><pres><p3><sg>` generates  туать    instead of тӑвать
`ту<v><tv><pres><p1><pl>` generates  туатпӑр    instead of тӑватпӑр
`ту<v><tv><pres><p2><pl>` generates  туатӑр    instead of тӑватӑр
(But p3.pl is correctly generated: тӑваҫҫӗ)

There is a similar problem for the future:
`ту<v><tv><fut><p1><sg>` generates  тувӑп    instead of тӑвӑп
`ту<v><tv><fut><p3><sg>` generates  тувӗ    instead of тӑвӗ
`ту<v><tv><fut><p1><pl>` generates  тувӑпӑр    instead of тӑвӑпӑр 
`ту<v><tv><fut><p2><pl>` generates  тувӑр    instead of тӑвӑр
`ту<v><tv><fut><p3><pl>` generates  тувӗҫ    instead of тӑвӗҫ  
(But p2.sg is correctly generated: тӑвӑн)
    
For some persons in imperative:
`ту<v><tv><imp><p3><sg>` generates  тувтӑр    instead of тутӑр
`ту<v><tv><imp><p2><pl>` generates  тувӑр    instead of тӑвӑр
`ту<v><tv><imp><p3><pl>` generates  тувччӑр    instead of туччӑр
 
More:
```
$ echo "^ту<v><tv><gpr_pres>$    " | hfst-proc -g chv.autogen.hfst
туакан  
```  
Should be тӑвакан
(But `ту<v><tv><gpr_fut>` is correctly generated: тӑвас)

The same problems can be found for тӳ,

**Comment by ftyers** [comment]
The underlying form is `ту{в}>{A}к{A}н`,
```
$ echo "ту<v><tv><gpr_pres>" | hfst-lookup .deps/chv.LR.lexc.hfst 
ту<v><tv><gpr_pres>	ту>{A}к{A}н	0,000000
ту<v><tv><gpr_pres>	ту{в}>{A}к{A}н	0,000000
```

should it be:

```
т у:ӑ {в}:в >:0 {A}:а к {A}:а н
```
?
Can you give examples for the other forms it is getting wrong? (it's much easier to fix when I have the data that includes the underlying form.)

**Comment by ftyers** [comment]
This appears to be the rule:

```

"Vowel reduction for high vowels before {в}"
Vx:Vy <=> _ %{в%}:в %>: [ %{и%}: %{н%}: | %{N%}: %{A%}: | н %{A%}: ] ;
          _ %{в%}:в %{☭%}: %>: %{и%}: %{н%}: ;
          _ %{в%}:в %>: %{Ă%}: н ;  ! genitive
          _ %{в%}:в %>: %{ă%}: м ;  ! px1sg
          _ %{в%}:в %>: %{Ĕ%}: р ;  ! px2pl
          _ %{в%}:в %>: %{U%}: ;  ! px2sg
          _ %{в%}:в %>: %{A%}: ;  ! verb forms
       where Vx in ( у ӳ )
             Vy in ( ӑ ӗ )
       matched ;
```
The morphotactic form is:
```
$ echo "ту<v><tv><pres><p1><sg>" | hfst-lookup .deps/chv.LR.lexc.hfst 
ту<v><tv><pres><p1><sg>	ту{в}>{A}т>{Ă}п	0,000000
```

Pair test gives:

```
$ echo "т у:ӑ {в}:в >:0 {A}:а т >:0 {Ă}:ӑ п" | hfst-pair-test .deps/chv.twol.hfst 

Rule "{в} doesn't surface before some suffixes" fails:
#:0 т у:ӑ {в}:в >:0 {A}:а HERE ---> т >:0 {Ă}:ӑ п #:0 

FAIL: т у:ӑ {в}:в >:0 {A}:а т >:0 {Ă}:ӑ п REJECTED

Test failed.
```

Ok, now I see:

```
"{в} doesn't surface before some suffixes"
%{в%}:0 <=> _ %>: [ %{T%}: %{A%}: | р %{A%}: | ш %{Ă%}: | м %{A%}: | н %{Ă%}: | %{A%}: [ т | к ] ] ;  ! Locative, abl, ter, neg, past, pres
            _ ([ :0 - %{☭%}: ]) %>: с ;  ! Plural
            _ ([ :0 - %{☭%}: ]) %>: п ; ! ins
            _ ([ :0 - %{☭%}: ]) .#. ;

!@ т у {в}:0 >:0 {T}:р {A}:а

!@ т у {в}:0 >:0 м {A}:а >:0 с {A}:а н
```

The problem is in the first context.

Fixed, at least for some of the values in 62b7018 .

```
ту<v><tv><pres><p1><sg>	тӑватӑп	0,000000
ту<v><tv><pres><p2><sg>	тӑватӑн	0,000000
ту<v><tv><pres><p3><sg>	тӑвать	0,000000
ту<v><tv><pres><p1><pl>	тӑватпӑр	0,000000
ту<v><tv><pres><p2><pl>	тӑватӑр	0,000000
ту<v><tv><pres><p3><pl>	тӑваҫҫӗ	0,000000
```

Fixed for future and imperative in 4d9cb12 .

```
ту<v><tv><fut><p1><sg>	тӑвӑп	0,000000
ту<v><tv><fut><p2><sg>	тӑвӑн	0,000000
ту<v><tv><fut><p3><sg>	тӑвӗ	0,000000
ту<v><tv><fut><p1><pl>	тӑвӑпӑр	0,000000
ту<v><tv><fut><p2><pl>	тӑвӑр	0,000000
ту<v><tv><fut><p3><pl>	тӑвӗҫ	0,000000
ту<v><tv><imp><p3><sg>	тутӑр	0,000000
ту<v><tv><imp><p2><pl>	тӑвӑр	0,000000
ту<v><tv><imp><p3><pl>	туччӑр	0,000000
```

**Comment by hectoralos** [comment]
Sorry, but I completely forgot these hfst commands. I'll try to use this  one from now.

It seems that these cases are solved, but I still see some issues where {в} is not deleted:

```
$ echo "ту<v><tv><neg><fut><p1><sg>" | hfst-lookup .deps/chv.LR.lexc.hfst 2>/dev/null
ту<v><tv><neg><fut><p1><sg>	ту{в}>м>{Ă}п	0,000000
```

Generates _тувмӑп_ instead of _тумӑп_ 

```
$ echo "ту<v><tv><neg><fut><p1><pl>" | hfst-lookup .deps/chv.LR.lexc.hfst 2>/dev/null
ту<v><tv><neg><fut><p1><pl>	ту{в}>м>{Ă}п{Ă}р	0,000000

```
Generates _тувмӑпӑр_ instead of _тумӑпӑр_

```
$ echo "ту<v><tv><neg><fut><p3><pl>" | hfst-lookup .deps/chv.LR.lexc.hfst 2>/dev/null
ту<v><tv><neg><fut><p3><pl>	ту{в}>м>{ӗ}ҫ	0,000000

```
Generates _тувмӗҫ_ instead of _тумӗҫ_

**Comment by ftyers** [comment]
Ok, fixed in 5e54cd0  
```
ту<v><tv><neg><fut><p1><sg>	тумӑп	0,000000
ту<v><tv><neg><fut><p2><sg>	тумӑн	0,000000
ту<v><tv><neg><fut><p3><sg>	тумӗ	0,000000
ту<v><tv><neg><fut><p1><pl>	тумӑпӑр	0,000000
ту<v><tv><neg><fut><p2><pl>	тумӑр	0,000000
ту<v><tv><neg><fut><p3><pl>	тумӗҫ	0,000000
```
